//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Settings/Input Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Input Controls"",
    ""maps"": [
        {
            ""name"": ""Player_KeyBoard"",
            ""id"": ""8ee50e16-d26e-4867-aa07-990f4426bddf"",
            ""actions"": [
                {
                    ""name"": ""MoveToLeft"",
                    ""type"": ""Button"",
                    ""id"": ""4f54a161-d735-4c4d-9107-b65fd0d992d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveToRight"",
                    ""type"": ""Button"",
                    ""id"": ""5442cced-1e11-4a01-9ffd-921f32be1630"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveToDown"",
                    ""type"": ""Button"",
                    ""id"": ""29b77873-dd02-4c19-aece-348290944a86"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HardDrop"",
                    ""type"": ""Button"",
                    ""id"": ""3587e309-bae8-426f-8e95-b188abd5432e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a0435c4f-53f5-4387-9813-9577076f8d8a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveToLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""511c8916-1adc-459e-8798-f21bc8ef969f"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveToLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f4c2580-18f3-497a-8544-1b8ae1686052"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveToRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e19d40e1-a04d-4161-80d0-8e22ad1b72b5"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveToRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70711e94-5a84-40a8-b51d-a1ef718e7c28"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveToDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ad2bf3b-228b-42df-ab68-34e9e2a3ca28"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveToDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""79137c59-2b7f-470b-abb3-b5e057577d77"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HardDrop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player_KeyBoard
        m_Player_KeyBoard = asset.FindActionMap("Player_KeyBoard", throwIfNotFound: true);
        m_Player_KeyBoard_MoveToLeft = m_Player_KeyBoard.FindAction("MoveToLeft", throwIfNotFound: true);
        m_Player_KeyBoard_MoveToRight = m_Player_KeyBoard.FindAction("MoveToRight", throwIfNotFound: true);
        m_Player_KeyBoard_MoveToDown = m_Player_KeyBoard.FindAction("MoveToDown", throwIfNotFound: true);
        m_Player_KeyBoard_HardDrop = m_Player_KeyBoard.FindAction("HardDrop", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player_KeyBoard
    private readonly InputActionMap m_Player_KeyBoard;
    private List<IPlayer_KeyBoardActions> m_Player_KeyBoardActionsCallbackInterfaces = new List<IPlayer_KeyBoardActions>();
    private readonly InputAction m_Player_KeyBoard_MoveToLeft;
    private readonly InputAction m_Player_KeyBoard_MoveToRight;
    private readonly InputAction m_Player_KeyBoard_MoveToDown;
    private readonly InputAction m_Player_KeyBoard_HardDrop;
    public struct Player_KeyBoardActions
    {
        private @InputControls m_Wrapper;
        public Player_KeyBoardActions(@InputControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveToLeft => m_Wrapper.m_Player_KeyBoard_MoveToLeft;
        public InputAction @MoveToRight => m_Wrapper.m_Player_KeyBoard_MoveToRight;
        public InputAction @MoveToDown => m_Wrapper.m_Player_KeyBoard_MoveToDown;
        public InputAction @HardDrop => m_Wrapper.m_Player_KeyBoard_HardDrop;
        public InputActionMap Get() { return m_Wrapper.m_Player_KeyBoard; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player_KeyBoardActions set) { return set.Get(); }
        public void AddCallbacks(IPlayer_KeyBoardActions instance)
        {
            if (instance == null || m_Wrapper.m_Player_KeyBoardActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Player_KeyBoardActionsCallbackInterfaces.Add(instance);
            @MoveToLeft.started += instance.OnMoveToLeft;
            @MoveToLeft.performed += instance.OnMoveToLeft;
            @MoveToLeft.canceled += instance.OnMoveToLeft;
            @MoveToRight.started += instance.OnMoveToRight;
            @MoveToRight.performed += instance.OnMoveToRight;
            @MoveToRight.canceled += instance.OnMoveToRight;
            @MoveToDown.started += instance.OnMoveToDown;
            @MoveToDown.performed += instance.OnMoveToDown;
            @MoveToDown.canceled += instance.OnMoveToDown;
            @HardDrop.started += instance.OnHardDrop;
            @HardDrop.performed += instance.OnHardDrop;
            @HardDrop.canceled += instance.OnHardDrop;
        }

        private void UnregisterCallbacks(IPlayer_KeyBoardActions instance)
        {
            @MoveToLeft.started -= instance.OnMoveToLeft;
            @MoveToLeft.performed -= instance.OnMoveToLeft;
            @MoveToLeft.canceled -= instance.OnMoveToLeft;
            @MoveToRight.started -= instance.OnMoveToRight;
            @MoveToRight.performed -= instance.OnMoveToRight;
            @MoveToRight.canceled -= instance.OnMoveToRight;
            @MoveToDown.started -= instance.OnMoveToDown;
            @MoveToDown.performed -= instance.OnMoveToDown;
            @MoveToDown.canceled -= instance.OnMoveToDown;
            @HardDrop.started -= instance.OnHardDrop;
            @HardDrop.performed -= instance.OnHardDrop;
            @HardDrop.canceled -= instance.OnHardDrop;
        }

        public void RemoveCallbacks(IPlayer_KeyBoardActions instance)
        {
            if (m_Wrapper.m_Player_KeyBoardActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayer_KeyBoardActions instance)
        {
            foreach (var item in m_Wrapper.m_Player_KeyBoardActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Player_KeyBoardActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Player_KeyBoardActions @Player_KeyBoard => new Player_KeyBoardActions(this);
    public interface IPlayer_KeyBoardActions
    {
        void OnMoveToLeft(InputAction.CallbackContext context);
        void OnMoveToRight(InputAction.CallbackContext context);
        void OnMoveToDown(InputAction.CallbackContext context);
        void OnHardDrop(InputAction.CallbackContext context);
    }
}
