//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/Settings/Input Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Settings/Input Controls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @InputControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @InputControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Input Controls"",
    ""maps"": [
        {
            ""name"": ""Player_KeyBoard"",
            ""id"": ""8ee50e16-d26e-4867-aa07-990f4426bddf"",
            ""actions"": [
                {
                    ""name"": ""MoveToLeft"",
                    ""type"": ""Button"",
                    ""id"": ""4f54a161-d735-4c4d-9107-b65fd0d992d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveToRight"",
                    ""type"": ""Button"",
                    ""id"": ""5442cced-1e11-4a01-9ffd-921f32be1630"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveToDown"",
                    ""type"": ""Button"",
                    ""id"": ""29b77873-dd02-4c19-aece-348290944a86"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HardDrop"",
                    ""type"": ""Button"",
                    ""id"": ""3587e309-bae8-426f-8e95-b188abd5432e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateToLeft"",
                    ""type"": ""Button"",
                    ""id"": ""8a63df87-80a9-4932-bb99-b1f5a3c750e2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateToRight"",
                    ""type"": ""Button"",
                    ""id"": ""72add2c2-485f-448b-a4ba-48207456b7e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a0435c4f-53f5-4387-9813-9577076f8d8a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveToLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""511c8916-1adc-459e-8798-f21bc8ef969f"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveToLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f4c2580-18f3-497a-8544-1b8ae1686052"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveToRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e19d40e1-a04d-4161-80d0-8e22ad1b72b5"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveToRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70711e94-5a84-40a8-b51d-a1ef718e7c28"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveToDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ad2bf3b-228b-42df-ab68-34e9e2a3ca28"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveToDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""79137c59-2b7f-470b-abb3-b5e057577d77"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HardDrop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec2195a1-606e-4fca-b618-bad90cec75bb"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateToLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00b8239e-541c-473d-8554-09ca93f8a3e7"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateToRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""269e9b9e-0894-49d4-8f3b-7eb1661088cc"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateToRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""216eb707-4013-4d04-9620-e230cf610747"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateToLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player_KeyBoard
        m_Player_KeyBoard = asset.FindActionMap("Player_KeyBoard", throwIfNotFound: true);
        m_Player_KeyBoard_MoveToLeft = m_Player_KeyBoard.FindAction("MoveToLeft", throwIfNotFound: true);
        m_Player_KeyBoard_MoveToRight = m_Player_KeyBoard.FindAction("MoveToRight", throwIfNotFound: true);
        m_Player_KeyBoard_MoveToDown = m_Player_KeyBoard.FindAction("MoveToDown", throwIfNotFound: true);
        m_Player_KeyBoard_HardDrop = m_Player_KeyBoard.FindAction("HardDrop", throwIfNotFound: true);
        m_Player_KeyBoard_RotateToLeft = m_Player_KeyBoard.FindAction("RotateToLeft", throwIfNotFound: true);
        m_Player_KeyBoard_RotateToRight = m_Player_KeyBoard.FindAction("RotateToRight", throwIfNotFound: true);
    }

    ~@InputControls()
    {
        UnityEngine.Debug.Assert(!m_Player_KeyBoard.enabled, "This will cause a leak and performance issues, InputControls.Player_KeyBoard.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player_KeyBoard
    private readonly InputActionMap m_Player_KeyBoard;
    private List<IPlayer_KeyBoardActions> m_Player_KeyBoardActionsCallbackInterfaces = new List<IPlayer_KeyBoardActions>();
    private readonly InputAction m_Player_KeyBoard_MoveToLeft;
    private readonly InputAction m_Player_KeyBoard_MoveToRight;
    private readonly InputAction m_Player_KeyBoard_MoveToDown;
    private readonly InputAction m_Player_KeyBoard_HardDrop;
    private readonly InputAction m_Player_KeyBoard_RotateToLeft;
    private readonly InputAction m_Player_KeyBoard_RotateToRight;
    /// <summary>
    /// Provides access to input actions defined in input action map "Player_KeyBoard".
    /// </summary>
    public struct Player_KeyBoardActions
    {
        private @InputControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public Player_KeyBoardActions(@InputControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Player_KeyBoard/MoveToLeft".
        /// </summary>
        public InputAction @MoveToLeft => m_Wrapper.m_Player_KeyBoard_MoveToLeft;
        /// <summary>
        /// Provides access to the underlying input action "Player_KeyBoard/MoveToRight".
        /// </summary>
        public InputAction @MoveToRight => m_Wrapper.m_Player_KeyBoard_MoveToRight;
        /// <summary>
        /// Provides access to the underlying input action "Player_KeyBoard/MoveToDown".
        /// </summary>
        public InputAction @MoveToDown => m_Wrapper.m_Player_KeyBoard_MoveToDown;
        /// <summary>
        /// Provides access to the underlying input action "Player_KeyBoard/HardDrop".
        /// </summary>
        public InputAction @HardDrop => m_Wrapper.m_Player_KeyBoard_HardDrop;
        /// <summary>
        /// Provides access to the underlying input action "Player_KeyBoard/RotateToLeft".
        /// </summary>
        public InputAction @RotateToLeft => m_Wrapper.m_Player_KeyBoard_RotateToLeft;
        /// <summary>
        /// Provides access to the underlying input action "Player_KeyBoard/RotateToRight".
        /// </summary>
        public InputAction @RotateToRight => m_Wrapper.m_Player_KeyBoard_RotateToRight;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Player_KeyBoard; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="Player_KeyBoardActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(Player_KeyBoardActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="Player_KeyBoardActions" />
        public void AddCallbacks(IPlayer_KeyBoardActions instance)
        {
            if (instance == null || m_Wrapper.m_Player_KeyBoardActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Player_KeyBoardActionsCallbackInterfaces.Add(instance);
            @MoveToLeft.started += instance.OnMoveToLeft;
            @MoveToLeft.performed += instance.OnMoveToLeft;
            @MoveToLeft.canceled += instance.OnMoveToLeft;
            @MoveToRight.started += instance.OnMoveToRight;
            @MoveToRight.performed += instance.OnMoveToRight;
            @MoveToRight.canceled += instance.OnMoveToRight;
            @MoveToDown.started += instance.OnMoveToDown;
            @MoveToDown.performed += instance.OnMoveToDown;
            @MoveToDown.canceled += instance.OnMoveToDown;
            @HardDrop.started += instance.OnHardDrop;
            @HardDrop.performed += instance.OnHardDrop;
            @HardDrop.canceled += instance.OnHardDrop;
            @RotateToLeft.started += instance.OnRotateToLeft;
            @RotateToLeft.performed += instance.OnRotateToLeft;
            @RotateToLeft.canceled += instance.OnRotateToLeft;
            @RotateToRight.started += instance.OnRotateToRight;
            @RotateToRight.performed += instance.OnRotateToRight;
            @RotateToRight.canceled += instance.OnRotateToRight;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="Player_KeyBoardActions" />
        private void UnregisterCallbacks(IPlayer_KeyBoardActions instance)
        {
            @MoveToLeft.started -= instance.OnMoveToLeft;
            @MoveToLeft.performed -= instance.OnMoveToLeft;
            @MoveToLeft.canceled -= instance.OnMoveToLeft;
            @MoveToRight.started -= instance.OnMoveToRight;
            @MoveToRight.performed -= instance.OnMoveToRight;
            @MoveToRight.canceled -= instance.OnMoveToRight;
            @MoveToDown.started -= instance.OnMoveToDown;
            @MoveToDown.performed -= instance.OnMoveToDown;
            @MoveToDown.canceled -= instance.OnMoveToDown;
            @HardDrop.started -= instance.OnHardDrop;
            @HardDrop.performed -= instance.OnHardDrop;
            @HardDrop.canceled -= instance.OnHardDrop;
            @RotateToLeft.started -= instance.OnRotateToLeft;
            @RotateToLeft.performed -= instance.OnRotateToLeft;
            @RotateToLeft.canceled -= instance.OnRotateToLeft;
            @RotateToRight.started -= instance.OnRotateToRight;
            @RotateToRight.performed -= instance.OnRotateToRight;
            @RotateToRight.canceled -= instance.OnRotateToRight;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="Player_KeyBoardActions.UnregisterCallbacks(IPlayer_KeyBoardActions)" />.
        /// </summary>
        /// <seealso cref="Player_KeyBoardActions.UnregisterCallbacks(IPlayer_KeyBoardActions)" />
        public void RemoveCallbacks(IPlayer_KeyBoardActions instance)
        {
            if (m_Wrapper.m_Player_KeyBoardActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="Player_KeyBoardActions.AddCallbacks(IPlayer_KeyBoardActions)" />
        /// <seealso cref="Player_KeyBoardActions.RemoveCallbacks(IPlayer_KeyBoardActions)" />
        /// <seealso cref="Player_KeyBoardActions.UnregisterCallbacks(IPlayer_KeyBoardActions)" />
        public void SetCallbacks(IPlayer_KeyBoardActions instance)
        {
            foreach (var item in m_Wrapper.m_Player_KeyBoardActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Player_KeyBoardActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="Player_KeyBoardActions" /> instance referencing this action map.
    /// </summary>
    public Player_KeyBoardActions @Player_KeyBoard => new Player_KeyBoardActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Player_KeyBoard" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="Player_KeyBoardActions.AddCallbacks(IPlayer_KeyBoardActions)" />
    /// <seealso cref="Player_KeyBoardActions.RemoveCallbacks(IPlayer_KeyBoardActions)" />
    public interface IPlayer_KeyBoardActions
    {
        /// <summary>
        /// Method invoked when associated input action "MoveToLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveToLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveToRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveToRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveToDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveToDown(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "HardDrop" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnHardDrop(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RotateToLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRotateToLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RotateToRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRotateToRight(InputAction.CallbackContext context);
    }
}
